package sys.model;
// Generated 01/11/2016 11:18:28 AM by Hibernate Tools 4.3.1



/**
 * Detallefactura generated by hbm2java
 */
public class Detallefactura  implements java.io.Serializable {


     private Integer codDetalle;
     private Factura factura;
     private Producto producto;
     private String codBarra;
     private String nombreProducto;
     private float precioVenta;
     private int cantidad;
     private double total;

    public Detallefactura() {
    }

    public Detallefactura(Factura factura, Producto producto,String codBarra,String nombreProducto, float precioVenta, int cantidad,double total) {
       this.factura = factura;
       this.producto = producto;
       this.codBarra=codBarra;
       this.nombreProducto=nombreProducto;
       this.precioVenta = precioVenta;
       this.cantidad = cantidad;
       this.total=total;
    }
   
    public Integer getCodDetalle() {
        return this.codDetalle;
    }
    
    public void setCodDetalle(Integer codDetalle) {
        this.codDetalle = codDetalle;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public String getCodBarra() {
        return codBarra;
    }

    public void setCodBarra(String codBarra) {
        this.codBarra = codBarra;
    }

    public String getNombreProducto() {
        return nombreProducto;
    }

    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    
    public float getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(float precioVenta) {
        this.precioVenta = precioVenta;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public double getTotal() {
        return total;
    }

    public void setTotal(double total) {
        this.total = total;
    }




}


